var num1=90,num2=50,num3=70;
if((num1>num2)&&(num1>num3))
{
    if(num2>num3)
    {
        console.log(num1,num2,num3);
    }
    else{
        console.log(num1,num3,num2);
    }
}
if((num2>num1)&&(num2>num3))
{
    if(num1>num3)
    {
        console.log(num1,num2,num3);
    }
    else{
        console.log(num1,num3,num2);
    }
}